---

version: 1
update_configs:
  - package_manager: "javascript"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
    directory: "/"
    update_schedule: "monthly"
    commit_message:
      prefix: "chore"
      include_scope: true
    default_reviewers:
      - bdronneau
