---

version: 1
update_configs:
  - package_manager: "javascript"
    automerged_updates: true
    directory: "/"
    update_schedule: "weekly"
    commit_message:
      prefix: "chore"
      include_scope: true
    default_reviewers:
      - bdronneau
